### ISSUE TITLE
Add Dedicated Strategy Section

### ISSUE THREAD

**Issue by jackschedel** [Solar-Gators/Pit-GUI#39]
- duplicate "Detailed Charts" section into "Strategy" section
- make SoC graph always 100-0
- auto-delete results w/ SoC of 0
- draw line of best fit
- have second "estimation" graph on the side that shows line of best fit going all the way to 0, factoring in remaining charges (user-settable)
- have 3 lines of best fit range, showing average case, worst case and best case (using r value)
- allow line of best fit to be only based on user-set range (click and drag)

**Comment by Seth10001** [comment]
> auto-delete results w/ SoC of 0

It might be nice to see the 0s sometimes, so maybe we make this a checkbox option?

**Comment by jackschedel** [comment]
note: regardless of checkbox option, don't factor those points into SoC line of best fit

**Comment by Seth10001** [comment]
Example line of best fit implementation with recharts: https://recharts.org/en-US/examples/ScatterAndLineOfBestFit
