### ISSUE TITLE
Expand API to allow for better chart implementation - requesting all datapoints of a single stat over a given timespan

### ISSUE THREAD

**Issue by jackschedel** [Solar-Gators/Pit-GUI#40]
chart loading is WAY too slow as it is currently

**Comment by Seth10001** [comment]
A first step would be only loading the "item" of the message that you care about. Right now the API only supports loading the entire message, so the SOC graph query looks like this:


 https://telemetry-api.ufsolargators.org/api/bms/rx4?where=%7B%22createdAt%22:%7B%22$gte%22:%222023-04-16+18:00%22,%22$lte%22:%222023-04-17+06:31%22%7D%7D
